HW3: HW3.o findMinMax.o
	gcc -o program HW3.o -o HW3
	gcc -o program findMinMax.o -o findMinMax

HW3.o: HW3.c
	gcc -c HW3.c

findMinMax.o: findMinMax.c
	gcc -c findMinMax.c

clean:
	rm *o findMinMax HW3
